data:
  build: .
  volumes:
    - .:/go/src/go_schedule
  command: 'true'

test:
  build: .
  volumes_from:
    - data
  command: gomon -t

build:
  build: .
  working_dir: /go/src/go_schedule
  volumes_from:
    - data
  command: gomon . -- go build 

run:
  build: .
  volumes_from:
    - data
  command: gomon src/go_schedule -- src/go_schedule/goSched.exe


